services:
  - type: web
    name: aplik-dashboard
    env: node
    region: ohio
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        value: postgresql://aplik_db_user:V0gJmG40vvCza763gjcbd5kDjSH7BIad@dpg-d8hgc3s2m8qs73b47hb0-a/aplik_db
      - key: NODE_VERSION
        value: "22"