services:
  - type: web
    name: aplik-dashboard
    env: node
    region: ohio
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_VERSION
        value: "22"
