// Datos iniciales migrados del Excel
// En producción esto vendría de Supabase

export const categories = [
  { id: 'pintura', name: 'Pintura', color: '#3498db' },
  { id: 'herramienta', name: 'Herramienta', color: '#e67e22' },
  { id: 'producto', name: 'Producto', color: '#2ecc71' },
];

export const products = [
  { id: 1, name: 'Vara de 8 a 16', category: 'herramienta', stock: 3, minStock: 5, unit: 'unidad' },
  { id: 2, name: 'Tubos Sellador Polyflex', category: 'producto', stock: 91, minStock: 20, unit: 'tubo' },
  { id: 3, name: 'Silicone Natural Ultra Clear', category: 'producto', stock: 0, minStock: 5, unit: 'unidad' },
  { id: 4, name: 'Rollo Lona 4mm', category: 'herramienta', stock: 32, minStock: 5, unit: 'rollo' },
  { id: 5, name: 'Porta Rolos Extrafuerte', category: 'herramienta', stock: 3, minStock: 3, unit: 'unidad' },
  { id: 6, name: 'Piedra de Pulir', category: 'herramienta', stock: 0, minStock: 5, unit: 'unidad' },
  { id: 7, name: 'Motas Rugosas', category: 'herramienta', stock: 6, minStock: 5, unit: 'unidad' },
  { id: 8, name: 'Motas Pequeñas Finas', category: 'herramienta', stock: 0, minStock: 5, unit: 'unidad' },
  { id: 9, name: 'Motas Extra Rugosa', category: 'herramienta', stock: 0, minStock: 5, unit: 'unidad' },
  { id: 10, name: 'Motas Anti Gota Lanco', category: 'herramienta', stock: 0, minStock: 5, unit: 'unidad' },
  { id: 11, name: 'Malla de Refuerzo', category: 'producto', stock: 1, minStock: 5, unit: 'unidad' },
  { id: 12, name: 'Gal Varsol', category: 'producto', stock: 5.5, minStock: 3, unit: 'galón' },
  { id: 13, name: 'Gal Semigloss Zero 6I3-8', category: 'pintura', stock: 0, minStock: 3, unit: 'galón' },
  { id: 14, name: 'Gal Seal Coat SW-6080', category: 'pintura', stock: 0, minStock: 3, unit: 'galón' },
  { id: 15, name: 'Gal Seal Coat Lino', category: 'pintura', stock: 0, minStock: 3, unit: 'galón' },
  { id: 16, name: 'Gal Seal Coat Arena del Sur', category: 'pintura', stock: 0, minStock: 3, unit: 'galón' },
  { id: 17, name: 'Gal Masilla Crack Filler', category: 'producto', stock: 1, minStock: 3, unit: 'galón' },
  { id: 18, name: 'Gal Lucidux Limpia Parabrisas', category: 'producto', stock: 1, minStock: 2, unit: 'galón' },
  { id: 19, name: 'Gal Galvacon', category: 'producto', stock: 0, minStock: 3, unit: 'galón' },
  { id: 20, name: 'Gal Durex 6L2-4 Gris', category: 'pintura', stock: 0, minStock: 2, unit: 'galón' },
  { id: 21, name: 'Gal Durex 1P3-7 Azul Claro', category: 'pintura', stock: 0, minStock: 2, unit: 'galón' },
  { id: 22, name: 'Gal Durex 1F3-8 Naranja Oscuro', category: 'pintura', stock: 0, minStock: 2, unit: 'galón' },
  { id: 23, name: 'Gal Durex 1C2-8 Rosado', category: 'pintura', stock: 0, minStock: 2, unit: 'galón' },
  { id: 24, name: 'Gal Durex 1A1-8 Morado', category: 'pintura', stock: 0, minStock: 2, unit: 'galón' },
  { id: 25, name: 'Gal Dry Coat', category: 'producto', stock: 0, minStock: 2, unit: 'galón' },
  { id: 26, name: 'Gal Citrus Cleaner', category: 'producto', stock: 0, minStock: 2, unit: 'galón' },
  { id: 27, name: 'Gal CB-Crete', category: 'producto', stock: 4, minStock: 3, unit: 'galón' },
  { id: 28, name: 'Express Lino Natural', category: 'pintura', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 29, name: 'Espátula Plástica', category: 'herramienta', stock: 0, minStock: 5, unit: 'unidad' },
  { id: 30, name: 'Espátula de Rosca', category: 'herramienta', stock: 0, minStock: 5, unit: 'unidad' },
  { id: 31, name: 'Cub Urethanizer', category: 'producto', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 32, name: 'Cub Ultra Siliconizer', category: 'producto', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 33, name: 'Cub Total Duna', category: 'pintura', stock: 6, minStock: 3, unit: 'cubeta' },
  { id: 34, name: 'Cub Total Blanco', category: 'pintura', stock: 18, minStock: 10, unit: 'cubeta' },
  { id: 35, name: 'Cub Texturizada Naranja', category: 'pintura', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 36, name: 'Cub Texturizada Blanco (Cano)', category: 'pintura', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 37, name: 'Cub Texturizada Blanco', category: 'pintura', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 38, name: 'Cub Texturizada Arena del Sur', category: 'pintura', stock: 8, minStock: 5, unit: 'cubeta' },
  { id: 39, name: 'Cub Super Track', category: 'producto', stock: 3, minStock: 3, unit: 'cubeta' },
  { id: 40, name: 'Cub Siliconizer Rojo Teja', category: 'producto', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 41, name: 'Cub Siliconizer 1000', category: 'producto', stock: 1, minStock: 3, unit: 'cubeta' },
  { id: 42, name: 'Cub Siliconizer', category: 'producto', stock: 0, minStock: 5, unit: 'cubeta' },
  { id: 43, name: 'Cub Semigloss Zero 6I3-3', category: 'pintura', stock: 0, minStock: 2, unit: 'cubeta' },
  { id: 44, name: 'Cub Seal Coat Verde Softball', category: 'pintura', stock: 0, minStock: 2, unit: 'cubeta' },
  { id: 45, name: 'Cub Seal Coat SM2-8 Verde Modif.', category: 'pintura', stock: 2, minStock: 3, unit: 'cubeta' },
  { id: 46, name: 'Cub Seal Coat N9-4', category: 'pintura', stock: 0, minStock: 2, unit: 'cubeta' },
  { id: 47, name: 'Cub Seal Coat Castaño', category: 'pintura', stock: 6, minStock: 5, unit: 'cubeta' },
  { id: 48, name: 'Cub Seal Coat Blanco', category: 'pintura', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 49, name: 'Cub Seal Coat 6L2-7', category: 'pintura', stock: 2, minStock: 3, unit: 'cubeta' },
  { id: 50, name: 'Cub Seal Coat 6L2-6', category: 'pintura', stock: 1, minStock: 3, unit: 'cubeta' },
  { id: 51, name: 'Cub Protecto Coat N8-4 Mindful', category: 'pintura', stock: 0, minStock: 2, unit: 'cubeta' },
  { id: 52, name: 'Cub Protecto Coat Blanco Mate', category: 'pintura', stock: 2, minStock: 3, unit: 'cubeta' },
  { id: 53, name: 'Cub Protecto Coat Arena del Sur', category: 'pintura', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 54, name: 'Cub Protecto Coat 6L2-4', category: 'pintura', stock: 0.75, minStock: 3, unit: 'cubeta' },
  { id: 55, name: 'Cub Protecto Coat 6J2-4', category: 'pintura', stock: 1, minStock: 3, unit: 'cubeta' },
  { id: 56, name: 'Cub Primer Super', category: 'producto', stock: 0, minStock: 5, unit: 'cubeta' },
  { id: 57, name: 'Cub Primer Sealer', category: 'producto', stock: 5, minStock: 5, unit: 'cubeta' },
  { id: 58, name: 'Cub Preseal', category: 'producto', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 59, name: 'Cub Microtop', category: 'producto', stock: 0, minStock: 10, unit: 'cubeta' },
  { id: 60, name: 'Cub Maxima Armor 6L2-7', category: 'pintura', stock: 0, minStock: 2, unit: 'cubeta' },
  { id: 61, name: 'Cub Maxima Armor 3R1-8', category: 'pintura', stock: 0, minStock: 2, unit: 'cubeta' },
  { id: 62, name: 'Cub Level Tech', category: 'producto', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 63, name: 'Cub Express Arena del Sur', category: 'pintura', stock: 0, minStock: 5, unit: 'cubeta' },
  { id: 64, name: 'Cub Express 6L2-4 Gris Sambil', category: 'pintura', stock: 0, minStock: 2, unit: 'cubeta' },
  { id: 65, name: 'Cub Duraflex', category: 'producto', stock: 0, minStock: 5, unit: 'cubeta' },
  { id: 66, name: 'Cub Cover Up Arena del Sur', category: 'pintura', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 67, name: 'Cub Cemento Plástico', category: 'producto', stock: 0, minStock: 5, unit: 'cubeta' },
  { id: 68, name: 'Cub CB-Crete', category: 'producto', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 69, name: 'Cub CB 1000', category: 'producto', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 70, name: 'Cub Aquaproof Wall', category: 'producto', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 71, name: 'Cub Aquaproof Primer', category: 'producto', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 72, name: 'Cub Aluminio', category: 'pintura', stock: 0, minStock: 5, unit: 'cubeta' },
  { id: 73, name: 'Cub Acrylflex', category: 'producto', stock: 0, minStock: 3, unit: 'cubeta' },
  { id: 74, name: 'Cinta Multi Seal', category: 'producto', stock: 0, minStock: 5, unit: 'unidad' },
  { id: 75, name: 'Cinta Ever Seal', category: 'producto', stock: 0, minStock: 5, unit: 'unidad' },
  { id: 76, name: 'Caja Masilla Joint Compound', category: 'producto', stock: 0, minStock: 5, unit: 'caja' },
  { id: 77, name: 'Rollo de Malla', category: 'herramienta', stock: 0, minStock: 3, unit: 'rollo' },
];

export const movements = [
  // Entradas (marzo - junio 2026)
  { id: 1, type: 'entrada', productId: 59, product: 'Cub Microtop', qty: 12, date: '2026-03-10', note: 'Compra Lanco' },
  { id: 2, type: 'entrada', productId: 63, product: 'Cub Express Arena del Sur', qty: 18, date: '2026-03-10', note: 'Compra Lanco' },
  { id: 3, type: 'entrada', productId: 65, product: 'Cub Duraflex', qty: 3, date: '2026-03-11', note: 'Devolución de Sambil' },
  { id: 4, type: 'entrada', productId: 63, product: 'Cub Express Arena del Sur', qty: 20, date: '2026-03-11', note: 'Compra Lanco' },
  { id: 5, type: 'entrada', productId: 28, product: 'Express Lino Natural', qty: 4, date: '2026-03-11', note: 'Compra Lanco' },
  { id: 6, type: 'entrada', productId: 76, product: 'Caja Masilla Joint Compound', qty: 6, date: '2026-03-11', note: 'Compra Lanco' },
  { id: 7, type: 'entrada', productId: 59, product: 'Cub Microtop', qty: 12, date: '2026-03-13', note: 'Compra Lanco' },
  { id: 8, type: 'entrada', productId: 34, product: 'Cub Total Blanco', qty: 20, date: '2026-03-14', note: 'Desde Almacén Panorama' },
  { id: 9, type: 'entrada', productId: 57, product: 'Cub Primer Sealer', qty: 10, date: '2026-03-14', note: 'Desde Almacén Panorama' },
  { id: 10, type: 'entrada', productId: 2, product: 'Tubos Sellador Polyflex', qty: 3, date: '2026-03-17', note: 'Devolución Sambil' },
  { id: 11, type: 'entrada', productId: 67, product: 'Cub Cemento Plástico', qty: 10, date: '2026-03-18', note: 'Compra Flexseal' },
  { id: 12, type: 'entrada', productId: 56, product: 'Cub Primer Super', qty: 10, date: '2026-03-18', note: 'Compra Flexseal' },
  { id: 13, type: 'entrada', productId: 65, product: 'Cub Duraflex', qty: 1.75, date: '2026-03-18', note: 'Devolución Mendoza' },
  { id: 14, type: 'entrada', productId: 53, product: 'Cub Protecto Coat Arena del Sur', qty: 2, date: '2026-03-19', note: 'Compra Lanco' },
  { id: 15, type: 'entrada', productId: 57, product: 'Cub Primer Sealer', qty: 10, date: '2026-03-20', note: 'Desde Panorama' },
  { id: 16, type: 'entrada', productId: 34, product: 'Cub Total Blanco', qty: 15, date: '2026-03-20', note: 'Desde Panorama' },
  { id: 17, type: 'entrada', productId: 42, product: 'Cub Siliconizer', qty: 30, date: '2026-03-21', note: 'Compra Lanco' },
  { id: 18, type: 'entrada', productId: 59, product: 'Cub Microtop', qty: 24, date: '2026-03-21', note: 'Compra Lanco' },
  { id: 19, type: 'entrada', productId: 71, product: 'Cub Aquaproof Primer', qty: 2, date: '2026-03-25', note: 'Devolución Carballo' },
  { id: 20, type: 'entrada', productId: 61, product: 'Cub Maxima Armor 3R1-8', qty: 2.75, date: '2026-03-25', note: 'Devolución Carballo' },
  { id: 21, type: 'entrada', productId: 34, product: 'Cub Total Blanco', qty: 20, date: '2026-03-28', note: 'Desde Panorama' },
  { id: 22, type: 'entrada', productId: 59, product: 'Cub Microtop', qty: 24, date: '2026-03-28', note: 'Compra Lanco' },
  // Abril
  { id: 23, type: 'entrada', productId: 34, product: 'Cub Total Blanco', qty: 12, date: '2026-04-10', note: 'Desde Panorama' },
  { id: 24, type: 'entrada', productId: 70, product: 'Cub Aquaproof Wall', qty: 6, date: '2026-04-10', note: 'Desde Panorama' },
  { id: 25, type: 'entrada', productId: 68, product: 'Cub CB-Crete', qty: 1, date: '2026-04-14', note: 'Desde Centro Olímpico' },
  { id: 26, type: 'entrada', productId: 31, product: 'Cub Urethanizer', qty: 11, date: '2026-04-14', note: 'Compra Lanco' },
  { id: 27, type: 'entrada', productId: 31, product: 'Cub Urethanizer', qty: 2, date: '2026-04-16', note: 'Devolución Aprecio Villa Faro' },
  { id: 28, type: 'entrada', productId: 45, product: 'Cub Seal Coat SM2-8 Verde Modif.', qty: 10, date: '2026-04-16', note: 'Compra Lanco' },
  { id: 29, type: 'entrada', productId: 47, product: 'Cub Seal Coat Castaño', qty: 12, date: '2026-04-27', note: 'Compra Lanco' },
  { id: 30, type: 'entrada', productId: 42, product: 'Cub Siliconizer', qty: 6, date: '2026-04-27', note: 'Compra Lanco' },
  { id: 31, type: 'entrada', productId: 72, product: 'Cub Aluminio', qty: 10, date: '2026-04-27', note: 'Compra Flexseal' },
  { id: 32, type: 'entrada', productId: 56, product: 'Cub Primer Super', qty: 10, date: '2026-04-27', note: 'Compra Flexseal' },
  // Mayo
  { id: 33, type: 'entrada', productId: 63, product: 'Cub Express Arena del Sur', qty: 10, date: '2026-05-05', note: 'Compra Lanco' },
  { id: 34, type: 'entrada', productId: 59, product: 'Cub Microtop', qty: 18, date: '2026-05-05', note: 'Compra Lanco' },
  { id: 35, type: 'entrada', productId: 65, product: 'Cub Duraflex', qty: 24, date: '2026-05-05', note: 'Compra Lanco' },
  { id: 36, type: 'entrada', productId: 59, product: 'Cub Microtop', qty: 24, date: '2026-05-11', note: 'Compra Lanco' },
  { id: 37, type: 'entrada', productId: 65, product: 'Cub Duraflex', qty: 18, date: '2026-05-11', note: 'Compra Lanco' },
  { id: 38, type: 'entrada', productId: 47, product: 'Cub Seal Coat Castaño', qty: 6, date: '2026-05-14', note: 'Compra Lanco' },
  { id: 39, type: 'entrada', productId: 28, product: 'Express Lino Natural', qty: 6, date: '2026-05-14', note: 'Compra Lanco' },
  { id: 40, type: 'entrada', productId: 56, product: 'Cub Primer Super', qty: 15, date: '2026-05-19', note: 'Compra Flexseal' },
  { id: 41, type: 'entrada', productId: 65, product: 'Cub Duraflex', qty: 18, date: '2026-05-19', note: 'Compra Lanco' },
  { id: 42, type: 'entrada', productId: 59, product: 'Cub Microtop', qty: 18, date: '2026-05-19', note: 'Compra Lanco' },
  // Salidas del Excel
  { id: 43, type: 'salida', productId: 34, product: 'Cub Total Blanco', qty: 4, date: '2026-03-07', destination: 'Centro Olímpico' },
  { id: 44, type: 'salida', productId: 59, product: 'Cub Microtop', qty: 2, date: '2026-03-09', destination: 'Centro Olímpico' },
  { id: 45, type: 'salida', productId: 57, product: 'Cub Primer Sealer', qty: 2, date: '2026-03-09', destination: 'Centro Olímpico' },
  { id: 46, type: 'salida', productId: 34, product: 'Cub Total Blanco', qty: 6, date: '2026-03-09', destination: 'Centro Olímpico' },
  { id: 47, type: 'salida', productId: 59, product: 'Cub Microtop', qty: 2, date: '2026-03-09', destination: 'Sambil' },
  { id: 48, type: 'salida', productId: 38, product: 'Cub Texturizada Arena del Sur', qty: 2, date: '2026-03-10', destination: 'Centro Olímpico' },
  { id: 49, type: 'salida', productId: 63, product: 'Cub Express Arena del Sur', qty: 10, date: '2026-03-10', destination: 'Centro Olímpico Área Piscinas' },
  { id: 50, type: 'salida', productId: 59, product: 'Cub Microtop', qty: 4, date: '2026-03-10', destination: 'Sambil' },
  { id: 51, type: 'salida', productId: 67, product: 'Cub Cemento Plástico', qty: 2, date: '2026-03-11', destination: 'Sambil' },
  { id: 52, type: 'salida', productId: 76, product: 'Caja Masilla Joint Compound', qty: 3, date: '2026-03-11', destination: 'Centro Olímpico' },
  { id: 53, type: 'salida', productId: 59, product: 'Cub Microtop', qty: 2, date: '2026-03-12', destination: 'Centro Olímpico' },
  { id: 54, type: 'salida', productId: 59, product: 'Cub Microtop', qty: 2, date: '2026-03-12', destination: 'Sambil' },
  { id: 55, type: 'salida', productId: 59, product: 'Cub Microtop', qty: 6, date: '2026-03-13', destination: 'Centro Olímpico' },
  { id: 56, type: 'salida', productId: 34, product: 'Cub Total Blanco', qty: 5, date: '2026-03-13', destination: 'Centro Olímpico' },
  { id: 57, type: 'salida', productId: 59, product: 'Cub Microtop', qty: 4, date: '2026-03-10', destination: 'Centro Olímpico' },
  { id: 58, type: 'salida', productId: 59, product: 'Cub Microtop', qty: 4, date: '2026-03-10', destination: 'Centro Olímpico' },
  { id: 59, type: 'salida', productId: 2, product: 'Tubos Sellador Polyflex', qty: 5, date: '2026-03-17', destination: 'Santísima Trinidad' },
  { id: 60, type: 'salida', productId: 63, product: 'Cub Express Arena del Sur', qty: 6, date: '2026-03-18', destination: 'Centro Olímpico' },
  { id: 61, type: 'salida', productId: 5, product: 'Porta Rolos Extrafuerte', qty: 3, date: '2026-03-18', destination: 'Centro Olímpico' },
  { id: 62, type: 'salida', productId: 7, product: 'Motas Rugosas', qty: 3, date: '2026-03-18', destination: 'Centro Olímpico' },
  { id: 63, type: 'salida', productId: 45, product: 'Cub Seal Coat SM2-8 Verde Modif.', qty: 2, date: '2026-03-17', destination: 'Centro Olímpico' },
  { id: 64, type: 'salida', productId: 17, product: 'Gal Masilla Crack Filler', qty: 1, date: '2026-03-18', destination: 'Sambil' },
  { id: 65, type: 'salida', productId: 69, product: 'Cub CB 1000', qty: 0.5, date: '2026-03-18', destination: 'Panorama' },
  { id: 66, type: 'salida', productId: 59, product: 'Cub Microtop', qty: 4, date: '2026-03-20', destination: 'Centro Olímpico' },
  { id: 67, type: 'salida', productId: 33, product: 'Cub Total Duna', qty: 3, date: '2026-03-17', destination: 'Centro Olímpico' },
  { id: 68, type: 'salida', productId: 12, product: 'Gal Varsol', qty: 0.5, date: '2026-02-14', destination: 'Centro Olímpico Área Piscinas' },
];

export const employees = [
  { id: 1, name: 'Mars', type: 'A', typeLabel: 'Buen Pintor', project: 'PYG', salary: 1350, discounts: 500 },
  { id: 2, name: 'Alann', type: 'A', typeLabel: 'Buen Pintor', project: 'Luxury', salary: 1350, discounts: 1500 },
  { id: 3, name: 'Luxama', type: 'A', typeLabel: 'Buen Pintor', project: 'PYG', salary: 1400, discounts: 500 },
  { id: 4, name: 'Casimir', type: 'A', typeLabel: 'Buen Pintor', project: 'PYG', salary: 1300, discounts: 1100 },
  { id: 5, name: 'Jonas', type: 'A', typeLabel: 'Buen Pintor', project: 'Luxury', salary: 1300, discounts: 500 },
  { id: 6, name: 'Remy', type: 'A', typeLabel: 'Buen Pintor', project: 'PYG', salary: 1200, discounts: 500 },
  { id: 7, name: 'Stanly', type: 'A', typeLabel: 'Buen Pintor', project: 'PYG', salary: 1100, discounts: 1100 },
  { id: 8, name: 'Louis', type: 'B', typeLabel: 'Pintor Intermedio', project: 'PYG', salary: 1100, discounts: 600 },
  { id: 9, name: 'Edwen', type: 'A', typeLabel: 'Buen Pintor', project: 'PYG', salary: 1100, discounts: 500 },
  { id: 10, name: 'Brebison', type: 'A', typeLabel: 'Buen Pintor', project: 'PYG', salary: 1100, discounts: 500 },
  { id: 11, name: 'Wender', type: 'B', typeLabel: 'Pintor Intermedio', project: 'PYG', salary: 1200, discounts: 0 },
  { id: 12, name: 'Daniel', type: 'B', typeLabel: 'Pintor Intermedio', project: 'Luxury', salary: 1100, discounts: 1100 },
  { id: 13, name: 'Ronaldino', type: 'B', typeLabel: 'Pintor Intermedio', project: 'PYG', salary: 1100, discounts: 500 },
  { id: 14, name: 'Vilasson', type: 'B', typeLabel: 'Pintor Intermedio', project: 'PYG', salary: 1100, discounts: 500 },
  { id: 15, name: 'Tito', type: 'C', typeLabel: 'Aprendiz', project: 'Luxury', salary: 1100, discounts: 600 },
  { id: 16, name: 'Fenel', type: 'M', typeLabel: 'Masillero', project: 'Luxury', salary: 1100, discounts: 500 },
  { id: 17, name: 'Florvil', type: 'M', typeLabel: 'Masillero', project: 'Luxury', salary: 1800, discounts: 600 },
  { id: 18, name: 'Wilken', type: 'C', typeLabel: 'Aprendiz', project: 'PYG', salary: 1800, discounts: 600 },
  { id: 19, name: 'Junior', type: 'C', typeLabel: 'Aprendiz', project: 'PYG', salary: 1100, discounts: 0 },
  { id: 20, name: 'Michelet', type: 'M', typeLabel: 'Masillero', project: 'Luxury', salary: 1100, discounts: 0 },
  { id: 21, name: 'Pierre', type: 'M', typeLabel: 'Masillero', project: 'Luxury', salary: 1800, discounts: 0 },
  { id: 22, name: 'Joseph Osse', type: 'M', typeLabel: 'Masillero', project: 'Luxury', salary: 1800, discounts: 0 },
  { id: 23, name: 'Widmacky', type: 'C', typeLabel: 'Aprendiz', project: 'PYG', salary: 1800, discounts: 0 },
  { id: 24, name: 'Luvin', type: 'C', typeLabel: 'Aprendiz', project: 'Luxury', salary: 1800, discounts: 600 },
  { id: 25, name: 'Dales', type: 'C', typeLabel: 'Aprendiz', project: 'PYG', salary: 1100, discounts: 0 },
  { id: 26, name: 'Edelson', type: 'C', typeLabel: 'Aprendiz', project: 'PYG', salary: 1100, discounts: 0 },
  { id: 27, name: 'Samuel', type: 'B', typeLabel: 'Pintor Intermedio', project: 'PYG', salary: 1100, discounts: 600 },
  { id: 28, name: 'Guimi', type: 'C', typeLabel: 'Aprendiz', project: 'PYG', salary: 1100, discounts: 600 },
];

// Asistencia de la primera quincena de junio
export const attendance = {
  period: '1ra Quincena Junio 2026',
  days: ['Lun 1', 'Mar 2', 'Mié 3', 'Jue 4', 'Vie 5', 'Sáb 6', 'Dom 7', 'Lun 8', 'Mar 9', 'Mié 10', 'Jue 11', 'Vie 12', 'Sáb 13', 'Dom 14', 'Lun 15'],
  records: [
    { employeeId: 1, days: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 2, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 3, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 4, days: [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 5, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 6, days: [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 7, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 8, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 9, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 10, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 11, days: [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 12, days: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 13, days: [0.5, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 14, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 15, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 16, days: [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 17, days: [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 18, days: [1, 0.5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 19, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 20, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 21, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 22, days: [0.5, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 23, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 24, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 25, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 26, days: [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 27, days: [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    { employeeId: 28, days: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
  ],
};